version: '3.9'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: test
  
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongo

  nodeserver:
    image: node:latest
    container_name: nodeserver
    ports:
      - 3000:3000
    volumes:
      - ./app:/app/
    working_dir: /app/
    entrypoint: /app/entrypoint.sh
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - mongo